# Generated by Django 3.2.19 on 2025-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('code', 'Programación'), ('video', 'Edición Video'), ('music', 'Producción Musical'), ('english', 'Inglés Técnico'), ('consulting', 'Asesoría')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
